language: python

python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"

before_install:
    - sudo apt-get update --quiet=2
    - sudo apt-get install --quiet=2 renameutils

install:
    - python setup.py --quiet install

script:
    - ./test.bash
