language: python

python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"

install:
    - python setup.py --quiet install

script:
    - mkdir -p ./.test/1
    - EDITOR=./fake move ./.test
    - ls ./.test/2
    - rm -rf ./.test
