sudo: false

language: python

python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"

addons:
    apt:
        packages:
            - renameutils

install:
    - python setup.py --quiet install

script:
    - rm -rf ./.test
    - mkdir -p ./.test/1
    - EDITOR=./fake move ./.test
    - ls ./.test/2
    - rm -rf ./.test
